language: php

sudo: required
dist: trusty
group: edge

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer clear-cache
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar

install: composer install

script: php phpunit.phar --configuration phpunit.xml tests


