<?php
/**
* A dialog field with a control that is generated by a callback, the control is xhtml.
*
* @copyright 2010 by papaya Software GmbH - All rights reserved.
* @link http://www.papaya-cms.com/
* @license http://www.gnu.org/licenses/old-licenses/gpl-2.0.html GNU General Public License, version 2
*
* You can redistribute and/or modify this script under the terms of the GNU General Public
* License (GPL) version 2, provided that the copyright and license notes, including these
* lines, remain unmodified. papaya is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.
*
* @package Papaya-Library
* @subpackage Ui
* @version $Id: Callback.php 37512 2012-09-06 13:53:04Z weinert $
*/

/**
* A dialog field with a control that is generated by a callback, the control is xhtml.
*
* @package Papaya-Library
* @subpackage Ui
*/
class PapayaUiDialogFieldXhtmlCallback extends PapayaUiDialogFieldCallback {

  /**
   *
   * @var boolean
   */
  protected $_isXhtml = TRUE;

}